-- Generated by the Organizer Library (12/15/17 17:52:13)
return {
    [1]={
        ["log_name"]="valorous mitts", 
        ["id"]=27139, 
        ["name"]="valorous mitts", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="rajas ring", 
        ["id"]=15543, 
        ["name"]="rajas ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="ioskeha belt", 
        ["id"]=26333, 
        ["name"]="ioskeha belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="breeze gorget", 
        ["id"]=15497, 
        ["name"]="breeze gorget", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="fire bomblet", 
        ["id"]=18707, 
        ["name"]="fire bomblet", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="mars's ring", 
        ["id"]=15548, 
        ["name"]="mars's ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="thunder belt", 
        ["id"]=11759, 
        ["name"]="thunder belt", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="twilight mail", 
        ["id"]=11362, 
        ["name"]="twilight mail", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="dark ring", 
        ["count"]=1, 
        ["id"]=14644, 
        ["name"]="dark ring", 
        ["augments"]={
            [1]="Phys. dmg. taken -5%", 
            [2]="Magic dmg. taken -5%"
        }
    }, 
    [11]={
        ["log_name"]="aptitude mantle +1", 
        ["id"]=27604, 
        ["name"]="aptitude mantle +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="valorous mail", 
        ["id"]=25717, 
        ["name"]="valorous mail", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="valorous mask", 
        ["id"]=25641, 
        ["name"]="valorous mask", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="valorous hose", 
        ["id"]=25841, 
        ["name"]="valor. hose", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="moonshade earring", 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="strigoi ring", 
        ["id"]=11628, 
        ["name"]="strigoi ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="moondoe mantle +1", 
        ["id"]=28595, 
        ["name"]="moondoe mantle +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="mache earring", 
        ["id"]=26080, 
        ["name"]="mache earring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="hermes' sandals", 
        ["id"]=11379, 
        ["name"]="hermes' sandals", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="valorous greaves", 
        ["id"]=27495, 
        ["name"]="valorous greaves", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="warrior's mufflers +2", 
        ["id"]=10690, 
        ["name"]="war. mufflers +2", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="warrior's cuisses +2", 
        ["id"]=10710, 
        ["name"]="war. cuisses +2", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="twilight helm", 
        ["id"]=11798, 
        ["name"]="twilight helm", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="agasaya's collar", 
        ["id"]=11622, 
        ["name"]="agasaya's collar", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="paguroidea ring", 
        ["id"]=10753, 
        ["name"]="paguroidea ring", 
        ["count"]=1
    }
}